### ISSUE TITLE
Player locality

### ISSUE THREAD

**Issue by StoneCypher** [jatlasd/gitchess#12]
One thing that isn't addressed here so far is the concept of player locality

* Is this a game for two humans at the same keyboard?  
* Is there any computer opponent afforded?  
* Can you seek anonymous player matching over the internet?  
* What about intentional matching with a known opponent?

This line of questions reflects something called [second system syndrome](https://en.wikipedia.org/wiki/Second-system_effect), wherein as something nears completion or reaches first version completion, the "next" version is weighed down with every single thing under the sun.

I ask these questions not because I want you to add these things, but rather, because I think it would be useful to intentionally decline them at this time, with the prudence of "for later" or "for never."  Indeed, I ***very strongly*** urge the current-time answers "yes, no, no, no."

Computer opponents are fun to write, but also difficult the first time around.  (Be happy to show you how, but, again, ***very strongly*** recommend that as a version 2+ feature.  Smart programmers cut the current version early; learn the phrases [YAGNI](https://wiki.c2.com/?YouArentGonnaNeedIt) and [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product).)

Anonymous player matching implies a server, and dealing with abusive players.  I'd honestly just completely pass on it.

Intentional matching, again, difficult the first time around; probably a version 2+ feature, but potentially worth your time.

Please concretely answer all four of those questions before closing this ticket.  This is a thinking ticket; close it at your leisure.

**Comment by jatlasd** [comment]
@StoneCypher Looking through all of your comments now. With regards to this one, the only thing that prompted me to make this at all was just to challenge myself with a more complex project than I'd attempted in the past. I had a brief, fleeting thought about making it actually playable but it quickly dissipated when I realized I had absolutely no idea how to do that and I just wanted to see if I could correctly create the game with rules. So, to answer your questions, yes, no, no, no. 

Side note - I tried to search for you on Discord and couldn't find anything.

**Comment by StoneCypher** [comment]
You're actually fairly close to a playable game

If you can display the game, and if you can interpret the rules, then:

1. You know whether a next-move is legal
2. You know whether to permit a move someone makes
3. You just need to update the internal board state and the display, then check for game over

**Comment by StoneCypher** [comment]
> Side note - I tried to search for you on Discord and couldn't find anything.

Try [here](https://discord.com/invite/9P95USqnMK)
